# Generated by Django 6.0 on 2026-05-15 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_customuser_company'),
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شاخص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('min_access_level', models.IntegerField(choices=[(1, 'کشور (ستاد مرکزی)'), (2, 'حوزه آبریز اصلی'), (3, 'استان (آب منطقه\u200cای)'), (4, 'شهرستان (امور آب)'), (5, 'بخش (واحد کارشناسی)'), (6, 'محدوده بهره\u200cبرداری (مزرعه/روستا)')], default=1, verbose_name='حداقل سطح دسترسی')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شاخص بهره\u200cوری آب',
                'verbose_name_plural': 'شاخص\u200cهای بهره\u200cوری آب',
            },
        ),
        migrations.RemoveField(
            model_name='variabledefinition',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='expertanswersubmission',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='expertanswerdetail',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='expertanswerdetail',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='expertanswersubmission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='expertanswersubmission',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='expertanswersubmission',
            name='region',
        ),
        migrations.RemoveField(
            model_name='variabledefinition',
            name='target_indicator',
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'ویدئو'), ('image', 'تصویر'), ('pdf', 'PDF'), ('document', 'مستند'), ('link', 'لینک')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='education/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('min_access_level', models.IntegerField(choices=[(1, 'کشور (ستاد مرکزی)'), (2, 'حوزه آبریز اصلی'), (3, 'استان (آب منطقه\u200cای)'), (4, 'شهرستان (امور آب)'), (5, 'بخش (واحد کارشناسی)'), (6, 'محدوده بهره\u200cبرداری (مزرعه/روستا)')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محتوای آموزشی',
                'verbose_name_plural': 'محتوای آموزشی',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_participation_rate', models.FloatField(default=0, verbose_name='درصد مشارکت کشاورزان')),
                ('expert_participation_rate', models.FloatField(default=0, verbose_name='درصد مشارکت کارشناسان')),
                ('total_farmers', models.IntegerField(default=0)),
                ('participating_farmers', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='accounts.region')),
            ],
            options={
                'verbose_name': 'وضعیت مشارکت',
                'verbose_name_plural': 'وضعیت مشارکت استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InputDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام داده ورودی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('data_type', models.CharField(choices=[('number', 'عددی'), ('text', 'متنی'), ('date', 'تاریخ')], max_length=20)),
                ('is_new_indicator', models.BooleanField(default=False)),
                ('new_indicator_name', models.CharField(blank=True, max_length=200)),
                ('new_indicator_unit', models.CharField(blank=True, max_length=50)),
                ('region_level', models.IntegerField(choices=[(1, 'کشور (ستاد مرکزی)'), (2, 'حوزه آبریز اصلی'), (3, 'استان (آب منطقه\u200cای)'), (4, 'شهرستان (امور آب)'), (5, 'بخش (واحد کارشناسی)'), (6, 'محدوده بهره\u200cبرداری (مزرعه/روستا)')], verbose_name='سطح منطقه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.waterindicator')),
            ],
            options={
                'verbose_name': 'درخواست داده ورودی',
                'verbose_name_plural': 'درخواست\u200cهای داده ورودی',
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='مقدار')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.waterindicator')),
            ],
            options={
                'verbose_name': 'مقدار شاخص',
                'verbose_name_plural': 'مقادیر شاخص\u200cها',
                'unique_together': {('indicator', 'region', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_comments', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='indicators.waterindicator')),
            ],
            options={
                'verbose_name': 'نظر شاخص',
                'verbose_name_plural': 'نظرات شاخص\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='ExpertAnswerDetail',
        ),
        migrations.DeleteModel(
            name='ExpertAnswerSubmission',
        ),
        migrations.DeleteModel(
            name='IndicatorDefinition',
        ),
        migrations.DeleteModel(
            name='VariableDefinition',
        ),
    ]
