# Generated by Django 6.0 on 2026-05-17 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_options_and_more'),
        ('indicators', '0002_waterindicator_remove_variabledefinition_crop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون یا اموجی (مثلاً 🌾)', max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': '۱. محصولات',
            },
        ),
        migrations.CreateModel(
            name='IndicatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شاخص')),
                ('formula', models.CharField(blank=True, help_text='فرمول را با ID متغیرها بنویسید. مثال: {1}/{2}', max_length=500, null=True, verbose_name='فرمول ریاضی')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد اندازه\u200cگیری')),
            ],
            options={
                'verbose_name': 'تعریف شاخص',
                'verbose_name_plural': '۲. تعریف شاخص\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='indicatorcomment',
            name='forwarded_to',
        ),
        migrations.RemoveField(
            model_name='indicatorcomment',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorcomment',
            name='region',
        ),
        migrations.RemoveField(
            model_name='indicatorcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='region',
        ),
        migrations.RemoveField(
            model_name='inputdatarequest',
            name='related_indicator',
        ),
        migrations.RemoveField(
            model_name='inputdatarequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='region',
        ),
        migrations.CreateModel(
            name='ExpertAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('verified', 'تایید شده'), ('rejected', 'نیاز به اصلاح')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='شرکت/سازمان')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.crop', verbose_name='محصول')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.region', verbose_name='بخش (لایه ۵)')),
            ],
            options={
                'verbose_name': 'پاسخ کارشناس',
                'verbose_name_plural': '۴. پاسخ\u200cهای ثبت شده',
            },
        ),
        migrations.CreateModel(
            name='VariableDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان سوال')),
                ('field_type', models.CharField(choices=[('number', 'عدد (اعشاری)'), ('integer', 'عدد (صحیح)'), ('text', 'متن کوتاه'), ('select', 'انتخابی (Dropdown)')], default='number', max_length=20, verbose_name='نوع فیلد ورودی')),
                ('options', models.TextField(blank=True, help_text='با ویرگول جدا کنید', null=True, verbose_name='گزینه\u200cها')),
                ('is_obsolete', models.BooleanField(default=False, verbose_name='داده قدیمی/منسوخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری است؟')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='indicators.crop', verbose_name='محصول مرتبط')),
                ('target_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicatordefinition', verbose_name='شاخص مرتبط')),
            ],
            options={
                'verbose_name': 'متغیر ورودی',
                'verbose_name_plural': '۳. متغیرهای ورودی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertAnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='مقدار ورودی')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='indicators.expertanswersubmission')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.variabledefinition')),
            ],
            options={
                'verbose_name': 'جزئیات پاسخ',
                'verbose_name_plural': '۵. جزئیات پاسخ\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='EducationalContent',
        ),
        migrations.DeleteModel(
            name='IndicatorComment',
        ),
        migrations.DeleteModel(
            name='IndicatorValue',
        ),
        migrations.DeleteModel(
            name='WaterIndicator',
        ),
        migrations.DeleteModel(
            name='InputDataRequest',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
