# Generated by Django 6.0 on 2026-05-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_crop_indicatordefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون دسته')),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'verbose_name_plural': '۰. دسته\u200cبندی محصولات',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='indicators.cropcategory', verbose_name='دسته محصول'),
        ),
    ]
