# Generated by Django 6.0 on 2026-05-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_options_and_more'),
        ('indicators', '0004_cropcategory_crop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledefinition',
            name='code',
            field=models.SlugField(default=2, help_text='کد انگلیسی یکتا (مثلاً: yield)', verbose_name='کد متغیر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='icon',
            field=models.CharField(blank=True, help_text='اموجی یا آیکون', max_length=50, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='expertanswerdetail',
            name='value',
            field=models.TextField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.region', verbose_name='منطقه (لایه ۵)'),
        ),
        migrations.AlterField(
            model_name='indicatordefinition',
            name='formula',
            field=models.CharField(blank=True, help_text='فرمول بر اساس کد متغیرها. مثال: yield/water', max_length=500, null=True, verbose_name='فرمول محاسباتی'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='field_type',
            field=models.CharField(choices=[('number', 'عدد (اعشاری)'), ('integer', 'عدد (صحیح)'), ('text', 'متن کوتاه'), ('select', 'انتخابی (Dropdown)')], default='number', max_length=20, verbose_name='نوع فیلد'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='is_obsolete',
            field=models.BooleanField(default=False, verbose_name='منسوخ شده'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='اجباری'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='target_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicatordefinition', verbose_name='شاخص عمومی مرتبط'),
        ),
        migrations.AlterUniqueTogether(
            name='variabledefinition',
            unique_together={('crop', 'code')},
        ),
    ]
