# Generated by Django 6.0 on 2026-05-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_variabledefinition_code_alter_crop_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variabledefinition',
            name='options',
        ),
        migrations.AddField(
            model_name='indicatordefinition',
            name='calculation_level',
            field=models.IntegerField(choices=[(1, 'ملی (ستاد)'), (2, 'حوضه آبریز'), (3, 'استانی'), (4, 'شهرستانی'), (5, 'بخش / مزرعه')], default=5, verbose_name='سطح محاسبه'),
        ),
        migrations.AddField(
            model_name='indicatordefinition',
            name='scope',
            field=models.CharField(choices=[('single', 'تک محصولی (اختصاصی)'), ('category', 'گروه محصولات (دسته خاص)'), ('all', 'عمومی (تمام محصولات)')], default='single', max_length=20, verbose_name='دامنه شمول'),
        ),
        migrations.AddField(
            model_name='indicatordefinition',
            name='target_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.cropcategory', verbose_name='دسته محصول هدف'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='field_type',
            field=models.CharField(default='number', max_length=20, verbose_name='نوع فیلد'),
        ),
    ]
