# Generated by Django 6.0 on 2026-05-17 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_options_and_more'),
        ('indicators', '0006_remove_variabledefinition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام خانواده گیاهی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات علمی')),
            ],
            options={
                'verbose_name': 'خانواده گیاهی',
                'verbose_name_plural': '۰.۱. خانواده\u200cهای گیاهی',
            },
        ),
        migrations.RemoveField(
            model_name='variabledefinition',
            name='is_required',
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='indicators.cropcategory', verbose_name='دسته'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='آیکون/اموجی'),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.region', verbose_name='بخش (لایه ۵)'),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('verified', 'تایید شده')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='expertanswersubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='indicatordefinition',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='فرمول (کد متغیر)'),
        ),
        migrations.AlterField(
            model_name='indicatordefinition',
            name='scope',
            field=models.CharField(choices=[('single', 'تک محصولی'), ('category', 'گروه محصولات (دسته)'), ('family', 'خانواده گیاهی'), ('all', 'عمومی (تمام محصولات)')], default='single', max_length=20, verbose_name='دامنه شمول'),
        ),
        migrations.AlterField(
            model_name='indicatordefinition',
            name='target_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.cropcategory', verbose_name='دسته هدف'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='code',
            field=models.SlugField(verbose_name='کد متغیر (در فرمول)'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='indicators.crop', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variabledefinition',
            name='target_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicatordefinition'),
        ),
        migrations.AddField(
            model_name='crop',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.cropfamily', verbose_name='خانواده'),
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رقم')),
                ('description', models.TextField(blank=True, verbose_name='ویژگی\u200cهای رقم')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='indicators.crop', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رقم محصول',
                'verbose_name_plural': '۱.۱. ارقام محصولات',
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.AddField(
            model_name='expertanswersubmission',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.cropvariety', verbose_name='رقم محصول'),
        ),
    ]
