# Generated by Django 6.0 on 2026-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "indicators",
            "0007_cropfamily_remove_variabledefinition_is_required_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="شناسه انگلیسی"
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="نام محصول (فارسی)"
            ),
        ),
        migrations.AlterField(
            model_name="indicatordefinition",
            name="formula",
            field=models.CharField(
                blank=True,
                help_text="مثال: yield / water",
                max_length=500,
                null=True,
                verbose_name="فرمول (کد عمومی)",
            ),
        ),
        migrations.AlterField(
            model_name="variabledefinition",
            name="code",
            field=models.SlugField(
                help_text="فقط کد پایه را بزنید، پسوند محصول خودکار اضافه می\u200cشود",
                verbose_name="کد پایه (مثلاً: yield)",
            ),
        ),
    ]
