# Generated by Django 6.0 on 2026-05-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0008_crop_slug_alter_crop_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crops",
                to="indicators.cropfamily",
                verbose_name="خانواده",
            ),
        ),
        migrations.AlterField(
            model_name="expertanswerdetail",
            name="value",
            field=models.DecimalField(
                decimal_places=3, max_digits=15, verbose_name="مقدار"
            ),
        ),
        migrations.AlterField(
            model_name="indicatordefinition",
            name="formula",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="فرمول (کد عمومی)"
            ),
        ),
        migrations.AlterField(
            model_name="variabledefinition",
            name="code",
            field=models.SlugField(verbose_name="کد پایه (مثلاً: yield)"),
        ),
    ]
