# Generated by Django 6.0 on 2026-05-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_experttask_crop_alter_activity_weight_and_more"),
        (
            "indicators",
            "0009_alter_crop_family_alter_expertanswerdetail_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variabledefinition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="variabledefinition",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicator_variables",
                to="accounts.activity",
                verbose_name="فعالیت مرتبط",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variabledefinition",
            unique_together={("crop", "activity", "code")},
        ),
    ]
