# Generated by Django 6.0 on 2026-06-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_experttask_assigned_by_experttask_parent_task_and_more"),
        ("indicators", "0010_alter_variabledefinition_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertanswersubmission",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.region",
                verbose_name="بخش (لایه ۵ یا بالاتر)",
            ),
        ),
        migrations.AlterField(
            model_name="expertanswersubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("submitted", "ارسال شده"),
                    ("verified", "تایید شده"),
                ],
                default="draft",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
