# Generated by Django 6.0 on 2026-02-11 17:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lng',
        ),
        migrations.AddField(
            model_name='customuser',
            name='expert_id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/experts/', verbose_name='کارت شناسایی کارشناس'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='موقعیت دقیق زمین'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farm_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmers/', verbose_name='تصویر سند مزرعه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('top_manager', 'مدیر کل شرکت مادر تخصصی'), ('region_manager', 'مدیر کل آب منطقه\u200cای استان'), ('city_manager', 'مدیر سازمان آب شهرستان'), ('staff', 'کارشناس بخش'), ('farmer', 'کشاورز')], default='farmer', max_length=20),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('level', models.IntegerField(choices=[(1, 'استان (مدیریت کل)'), (2, 'شهرستان (مدیر شهرستان)'), (3, 'بخش (حوزه کارشناس)')], verbose_name='سطح مدیریتی')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='مرز جغرافیایی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_regions', to='accounts.region')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='منطقه تحت مسئولیت'),
        ),
    ]
