# Generated by Django 6.0 on 2026-02-11 23:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_lat_remove_customuser_lng_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'منطقه', 'verbose_name_plural': 'مناطق'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_region',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='chosen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='منطقه تحت پوشش / محل زمین'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('top_manager', 'مدیر کل شرکت مادر تخصصی'), ('region_manager', 'مدیر کل آب منطقه\u200cای استان'), ('city_manager', 'مدیر سازمان آب شهرستان'), ('staff', 'کارشناس بخش'), ('farmer', 'کشاورز')], default='farmer', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='مرز جغرافیایی'),
        ),
    ]
