# Generated by Django 6.0 on 2026-02-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expert_id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/experts/', verbose_name='کارت کارشناس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farm_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmers/', verbose_name='سند مزرعه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('top_manager', 'مدیر کل شرکت مادر تخصصی'), ('region_manager', 'مدیر کل آب منطقه\u200cای استان'), ('city_manager', 'مدیر سازمان آب شهرستان'), ('staff', 'کارشناس بخش'), ('farmer', 'کشاورز')], default='farmer', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_regions', to='accounts.region', verbose_name='منطقه بالادست'),
        ),
    ]
