# Generated by Django 6.0 on 2026-02-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_expert_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.IntegerField(choices=[(1, 'استان '), (2, 'شهرستان '), (3, 'بخش ')], verbose_name='سطح مدیریتی'),
        ),
    ]
