# Generated by Django 6.0 on 2026-02-17 12:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_region_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.region', verbose_name='مناطق تحت مدیریت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='محدوده هندسی اختصاصی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chosen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='منطقه محل زمین (برای کشاورز)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.IntegerField(choices=[(1, 'استان'), (2, 'شهرستان'), (3, 'بخش')], verbose_name='سطح مدیریتی'),
        ),
    ]
