# Generated by Django 6.0 on 2026-02-20 13:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_managed_regions_customuser_user_geometry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
