# Generated by Django 6.0 on 2026-04-13 10:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_region_polygon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'مدیریت کاربران'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'واحد جغرافیایی', 'verbose_name_plural': 'تقسیمات حوزه\u200cای و کشوری'},
        ),
        migrations.AddField(
            model_name='region',
            name='is_watershed',
            field=models.BooleanField(default=True, verbose_name='ماهیت حوزه\u200cای (آبی) دارد؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chosen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='محدوده فعالیت (زیرحوزه/روستا)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expert_id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/experts/', verbose_name='کارت شناسایی کارشناس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farm_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmers/', verbose_name='اسناد بهره\u200cبرداری'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='وضعیت تایید صلاحیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.region', verbose_name='قلمرو تحت مدیریت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر ارشد سامانه'), ('top_manager', 'ستاد ملی پایش منابع آب (کشور)'), ('watershed_manager', 'مدیر کل حوزه آبریز (مرز هیدرولوژیک)'), ('province_manager', 'مدیر کل آب منطقه\u200cای (مرز استانی)'), ('city_manager', 'مدیر منابع آب شهرستان'), ('staff', 'کارشناس پایش و بازرسی'), ('farmer', 'بهره\u200cبردار (ذینفع نهایی)')], default='farmer', max_length=20, verbose_name='سمت مدیریتی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='پلیگون اختصاصی ذینفع'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='مرز جغرافیایی (GIS)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.IntegerField(choices=[(1, 'حوزه آبریز اصلی (ستادی)'), (2, 'مدیریت منطقه / واحد استانی'), (3, 'زیرحوزه / محدوده عملیاتی شهرستان'), (4, 'واحد بهره\u200cبرداری / روستا')], verbose_name='سطح ساختار'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام واحد'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_regions', to='accounts.region', verbose_name='واحد بالادست'),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='پلیگون اختصاصی'),
        ),
    ]
