# Generated by Django 6.0 on 2026-04-13 11:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'منطقه/واحد', 'verbose_name_plural': 'تقسیمات مدیریت آب'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chosen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='منطقه محل فعالیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farm_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/farmers/', verbose_name='سند/پروانه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید صلاحیت شده'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.region', verbose_name='مناطق تحت مدیریت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('top_manager', '۱. مدیر کل شرکت مادر تخصصی'), ('watershed_manager', '۲. مدیر حوزه آبریز اصلی کشور'), ('province_manager', '۳. مدیر کل آب منطقه\u200cای استان'), ('city_manager', '۴. مدیر سازمان آب شهرستان'), ('staff', '۵. کارشناس بخش'), ('farmer', '۶. بهره\u200cبردار و کشاورز'), ('admin', 'مدیر سیستم (IT)')], default='farmer', max_length=20, verbose_name='نقش مدیریتی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='هندسه اختصاصی ذینفع'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_watershed',
            field=models.BooleanField(default=True, verbose_name='ماهیت هیدرولوژیک (آبی)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.IntegerField(choices=[(1, 'کشور (ستاد مرکزی)'), (2, 'حوزه آبریز اصلی'), (3, 'استان (آب منطقه\u200cای)'), (4, 'شهرستان (امور آب)'), (5, 'بخش (واحد کارشناسی)'), (6, 'محدوده بهره\u200cبرداری (مزرعه/روستا)')], verbose_name='سطح مدیریتی'),
        ),
    ]
