# Generated by Django 6.0 on 2026-04-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_region_options_alter_customuser_chosen_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chosen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='accounts.region', verbose_name='منطقه محل فعالیت'),
        ),
    ]
