# Generated by Django 6.0 on 2026-05-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_chosen_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت/سازمان')),
                ('business_type', models.CharField(choices=[('agri', 'جهاد کشاورزی'), ('water', 'مدیریت منابع آب')], default='agri', max_length=50, verbose_name='حوزه فعالیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
            ],
            options={
                'verbose_name': 'سازمان / شرکت',
                'verbose_name_plural': 'سازمان\u200cها و شرکت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.company', verbose_name='شرکت/سازمان متبوع'),
        ),
    ]
