# Generated by Django 6.0 on 2026-05-17 09:27

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_customuser_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='expert_id_card',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farm_document',
        ),
        migrations.RemoveField(
            model_name='region',
            name='geom',
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_export',
            field=models.BooleanField(default=True, verbose_name='دسترسی به خروجی اکسل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_indicators',
            field=models.BooleanField(default=True, verbose_name='دسترسی به شاخص\u200cها'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_maps',
            field=models.BooleanField(default=True, verbose_name='دسترسی به نقشه\u200cها'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_training',
            field=models.BooleanField(default=True, verbose_name='دسترسی به مرکز آموزش'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('agri', 'جهاد کشاورزی'), ('water', 'مدیریت منابع آب')], default='water', max_length=50, verbose_name='حوزه فعالیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='chosen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='accounts.region', verbose_name='منطقه فعالیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.company', verbose_name='سازمان'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.region', verbose_name='مناطق تحت نظارت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست.', regex='^09\\d{9}$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='هندسه اختصاصی'),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='مرز جغرافیایی (GIS)'),
        ),
    ]
