# Generated by Django 6.0 on 2026-05-18 09:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326, verbose_name="مرز جغرافیایی (GIS)"
            ),
        ),
    ]
