# Generated by Django 6.0 on 2026-05-20 10:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_region_geom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "verbose_name": "ساختار سازمانی",
                "verbose_name_plural": "چارت سازمانی",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "verbose_name": "منطقه جغرافیایی",
                "verbose_name_plural": "مناطق و تقسیمات",
            },
        ),
        migrations.RemoveField(
            model_name="company",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="access_export",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="access_indicators",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="access_maps",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="access_training",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="managed_regions",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_geometry",
        ),
        migrations.RemoveField(
            model_name="region",
            name="is_watershed",
        ),
        migrations.RemoveField(
            model_name="region",
            name="polygon",
        ),
        migrations.AddField(
            model_name="company",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("agri", "وزارت جهاد کشاورزی"),
                    ("water", "وزارت نیرو (شرکت منابع آب)"),
                ],
                default="water",
                max_length=10,
                verbose_name="وزارتخانه مرجع",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_units",
                to="accounts.company",
                verbose_name="واحد بالادست",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="managed_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="accounts.region",
                verbose_name="منطقه تحت مدیریت",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="office_level",
            field=models.CharField(
                choices=[
                    ("national", "ستاد مرکزی (کشوری)"),
                    ("province", "سطح استان"),
                    ("city", "سطح شهرستان"),
                    ("section", "سطح بخش"),
                ],
                default="province",
                max_length=20,
                verbose_name="سطح فعالیت",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("head", "مدیر کل / رئیس واحد"),
                    ("deputy", "معاون مدیر"),
                    ("group_leader", "مدیر گروه / رئیس اداره"),
                    ("expert", "کارشناس مسئول"),
                    ("staff", "کارشناس عملیاتی"),
                    ("farmer", "بهره\u200cبردار (کشاورز)"),
                ],
                default="staff",
                max_length=20,
                verbose_name="سمت اداری",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="نام واحد/معاونت/سازمان/دفتر"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="chosen_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="local_farmers",
                to="accounts.region",
                verbose_name="منطقه فعالیت کشاورز",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.company",
                verbose_name="واحد خدمتی",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="تایید صلاحیت"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="national_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326, verbose_name="مرز جغرافیایی"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "کشور (ستاد مرکزی)"),
                    (2, "حوزه آبریز / قطب کشاورزی"),
                    (3, "استان"),
                    (4, "شهرستان"),
                    (5, "بخش"),
                    (6, "محدوده بهره\u200cبرداری (مزرعه / روستا)"),
                ],
                verbose_name="سطح تقسیمات",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام منطقه"),
        ),
        migrations.AlterField(
            model_name="region",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_regions",
                to="accounts.region",
                verbose_name="منطقه بالادست",
            ),
        ),
    ]
