# Generated by Django 6.0 on 2026-05-20 14:12

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_company_options_alter_region_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerUser",
            fields=[],
            options={
                "verbose_name": "بهره\u200cبردار (کشاورز)",
                "verbose_name_plural": "مدیریت کشاورزان",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OfficialUser",
            fields=[],
            options={
                "verbose_name": "پرسنل اداری",
                "verbose_name_plural": "مدیریت پرسنل اداری",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="accounts.region",
                verbose_name="منطقه استقرار واحد",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("official", "پرسنل اداری / دولتی"),
                    ("farmer", "بهره\u200cبردار (کشاورز)"),
                ],
                default="official",
                max_length=10,
                verbose_name="نوع کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="managed_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="accounts.region",
                verbose_name="منطقه تحت مدیریت (اداری)",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="office_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national", "ستاد مرکزی (کشوری)"),
                    ("province", "سطح استان"),
                    ("city", "سطح شهرستان"),
                    ("section", "سطح بخش"),
                ],
                max_length=20,
                null=True,
                verbose_name="سطح فعالیت",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("head", "مدیر کل / رئیس واحد"),
                    ("deputy", "معاون مدیر"),
                    ("group_leader", "مدیر گروه / رئیس اداره"),
                    ("expert", "کارشناس مسئول"),
                    ("staff", "کارشناس عملیاتی"),
                ],
                max_length=20,
                null=True,
                verbose_name="سمت اداری",
            ),
        ),
    ]
