# Generated by Django 6.0 on 2026-05-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_farmeruser_officialuser_company_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان فعالیت"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="شرح استاندارد فعالیت"),
                ),
                (
                    "org_type_limit",
                    models.CharField(
                        choices=[("agri", "کشاورزی"), ("water", "آب")],
                        max_length=10,
                        verbose_name="مربوط به حوزه (وزارتخانه)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعریف فعالیت",
                "verbose_name_plural": "۱. بانک فعالیت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ExpertTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="وضعیت ابلاغیه"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.activity",
                        verbose_name="فعالیت محوله",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "official"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارشناس مسئول",
                    ),
                ),
                (
                    "target_regions",
                    models.ManyToManyField(
                        related_name="assigned_tasks",
                        to="accounts.region",
                        verbose_name="روستاها/مناطق تحت پوشش",
                    ),
                ),
            ],
            options={
                "verbose_name": "ابلاغ وظیفه",
                "verbose_name_plural": "۳. ابلاغ وظایف به کارشناسان",
            },
        ),
        migrations.CreateModel(
            name="ActivityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="accounts.activity",
                        verbose_name="فعالیت",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_activities",
                        to="accounts.company",
                        verbose_name="سازمان متولی",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص سازمانی",
                "verbose_name_plural": "۲. تخصیص فعالیت به سازمان",
                "unique_together": {("activity", "company")},
            },
        ),
    ]
