# Generated by Django 6.0 on 2026-05-24 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_activity_experttask_activityassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="at_city_level",
            field=models.BooleanField(
                default=False, verbose_name="فعال در تمام شهرستان\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="at_national_level",
            field=models.BooleanField(default=False, verbose_name="فعال در سطح کشوری"),
        ),
        migrations.AddField(
            model_name="company",
            name="at_province_level",
            field=models.BooleanField(
                default=False, verbose_name="فعال در تمام استان\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="at_section_level",
            field=models.BooleanField(
                default=False, verbose_name="فعال در تمام بخش\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="اگر تیک بخورد، این واحد به عنوان یک مدل مرجع برای کپی شدن در سطوح مختلف استفاده می\u200cشود.",
                verbose_name="به عنوان الگوی ساختار (Template)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="org_type",
            field=models.CharField(
                choices=[("agri", "وزارت جهاد کشاورزی"), ("water", "وزارت نیرو ")],
                max_length=10,
                verbose_name="وزارتخانه مرجع",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="expert",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "official"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارشناس مسئول",
            ),
        ),
    ]
