# Generated by Django 6.0 on 2026-05-24 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_company_at_city_level_company_at_national_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmeruser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="officialuser",
            options={},
        ),
        migrations.AlterField(
            model_name="activity",
            name="org_type_limit",
            field=models.CharField(
                choices=[("agri", "کشاورزی"), ("water", "آب")],
                max_length=10,
                verbose_name="مربوط به حوزه",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="اگر الگو باشد، فیلد منطقه باید خالی بماند.",
                verbose_name="به عنوان الگوی ساختار (Template)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("agri", "وزارت جهاد کشاورزی"),
                    ("water", "وزارت نیرو (شرکت منابع آب)"),
                ],
                max_length=10,
                verbose_name="وزارتخانه مرجع",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارشناس مسئول",
            ),
        ),
    ]
