# Generated by Django 6.0 on 2026-05-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0018_alter_farmeruser_options_alter_officialuser_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmeruser",
            options={
                "verbose_name": "بهره\u200cبردار (کشاورز)",
                "verbose_name_plural": "مدیریت کشاورزان",
            },
        ),
        migrations.AlterModelOptions(
            name="officialuser",
            options={
                "verbose_name": "پرسنل اداری",
                "verbose_name_plural": "مدیریت پرسنل اداری",
            },
        ),
    ]
