# Generated by Django 6.0 on 2026-05-25 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_farmeruser_options_alter_officialuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "verbose_name": "فعالیت و وظیفه",
                "verbose_name_plural": "ساختار فعالیت\u200cها و وظایف",
            },
        ),
        migrations.AlterModelOptions(
            name="experttask",
            options={
                "verbose_name": "ابلاغ وظیفه",
                "verbose_name_plural": "ابلاغ وظایف و نظارت",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="assigned_companies",
            field=models.ManyToManyField(
                related_name="activities",
                to="accounts.company",
                verbose_name="سازمان\u200cهای متولی",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_activities",
                to="accounts.activity",
                verbose_name="فعالیت بالادست",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="self_progress",
            field=models.PositiveIntegerField(
                default=0, verbose_name="پیشرفت اعلامی کارشناس"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="verified_progress",
            field=models.PositiveIntegerField(
                default=0, verbose_name="پیشرفت تایید شده نهایی"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="weight",
            field=models.PositiveIntegerField(
                default=1,
                help_text="درصد اهمیت این بخش نسبت به فعالیت مادر (بین ۱ تا ۱۰۰)",
                verbose_name="وزن (اهمیت)",
            ),
        ),
        migrations.AddField(
            model_name="experttask",
            name="manager_comment",
            field=models.TextField(blank=True, verbose_name="توضیحات مدیر"),
        ),
        migrations.AddField(
            model_name="experttask",
            name="progress_report",
            field=models.PositiveIntegerField(
                default=0, verbose_name="درصد پیشرفت گزارش شده"
            ),
        ),
        migrations.AddField(
            model_name="experttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار انجام"),
                    ("submitted", "ارسال شده برای تایید"),
                    ("approved", "تایید شده نهایی"),
                    ("rejected", "نیاز به اصلاح"),
                ],
                default="pending",
                max_length=15,
                verbose_name="وضعیت تایید",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, verbose_name="شرح استاندارد"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="org_type_limit",
            field=models.CharField(
                choices=[("agri", "کشاورزی"), ("water", "آب")],
                max_length=10,
                verbose_name="حوزه مربوطه",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="title",
            field=models.CharField(max_length=250, verbose_name="عنوان فعالیت/وظیفه"),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.activity",
                verbose_name="فعالیت/وظیفه محوله",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول (کارشناس/مدیر)",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="target_regions",
            field=models.ManyToManyField(
                related_name="assigned_tasks",
                to="accounts.region",
                verbose_name="مناطق تحت پوشش",
            ),
        ),
        migrations.DeleteModel(
            name="ActivityAssignment",
        ),
    ]
