# Generated by Django 6.0 on 2026-05-25 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_activity_options_alter_experttask_options_and_more"),
        (
            "indicators",
            "0009_alter_crop_family_alter_expertanswerdetail_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="experttask",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.crop",
                verbose_name="محصول مرتبط (از سامانه شاخص\u200cها)",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="weight",
            field=models.PositiveIntegerField(default=1, verbose_name="وزن (اهمیت)"),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول",
            ),
        ),
    ]
