# Generated by Django 6.0 on 2026-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_experttask_crop_alter_activity_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="can_approve_farmers",
            field=models.BooleanField(
                default=False,
                verbose_name="دارای دسترسی تایید صلاحیت کشاورزان زیرمجموعه",
            ),
        ),
    ]
