# Generated by Django 6.0 on 2026-06-20 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_customuser_can_approve_farmers"),
        ("indicators", "0010_alter_variabledefinition_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experttask",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ارجاع\u200cدهنده وظیفه",
            ),
        ),
        migrations.AddField(
            model_name="experttask",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_tasks",
                to="accounts.experttask",
                verbose_name="وظیفه مبدا بالادست",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="indicators.crop",
                verbose_name="محصول مرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسئول فعلی",
            ),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="manager_comment",
            field=models.TextField(blank=True, verbose_name="توضیحات و دلایل رد کار"),
        ),
        migrations.AlterField(
            model_name="experttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_assignment", "در انتظار ارجاع و تقسیم وظایف"),
                    ("pending", "در انتظار پاسخ و ثبت متغیرها"),
                    ("submitted", "ارسال شده برای بررسی بالادست"),
                    ("approved", "تایید شده نهایی"),
                    ("rejected", "رد شده / نیازمند اصلاح زیرمجموعه"),
                ],
                default="pending_assignment",
                max_length=25,
                verbose_name="وضعیت تایید",
            ),
        ),
    ]
