# Generated by Django 6.0 on 2026-07-10 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_experttask_assigned_by_experttask_parent_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experttask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="زمان ایجاد ارجاع",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experttask",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="دلیل رد فعالیت"
            ),
        ),
    ]
