# Generated by Django 6.1.1 on 2026-10-02 13:39

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_review_fields_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='self_progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='پیشرفت اعلامی کارشناس'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='verified_progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='پیشرفت تایید شده نهایی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[accounts.models.validate_national_code], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با ۰۹ شروع شود و دقیقاً ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='experttask',
            name='progress_report',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت گزارش شده'),
        ),
    ]
