# Generated by Django 6.0 on 2026-02-05 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پرسشنامه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پرسشنامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن سوال')),
                ('type', models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن طولانی (تشریحی)'), ('number', 'عدد'), ('radio', 'تک انتخابی (گزینه\u200cای)')], default='text', max_length=20, verbose_name='نوع سوال')),
                ('choices', models.CharField(blank=True, help_text='گزینه\u200cها را با ویرگول (,) جدا کنید. (فقط برای نوع گزینه\u200cای)', max_length=500, null=True, verbose_name='گزینه\u200cها')),
                ('required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='پرسشنامه')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(verbose_name='پاسخ ثبت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
