# Generated by Django 6.0 on 2026-05-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_customuser_company'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'پرسشنامه', 'verbose_name_plural': 'پرسشنامه\u200cها'},
        ),
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='accounts.company', verbose_name='شرکت/سازمان مرتبط'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعالیت'),
        ),
    ]
