# Generated by Django 6.0 on 2026-06-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_experttask_crop_alter_activity_weight_and_more"),
        ("indicators", "0010_alter_variabledefinition_unique_together_and_more"),
        ("surveys", "0002_alter_question_options_alter_survey_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "پاسخ",
                "verbose_name_plural": "۳. بانک پاسخ\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "سوال", "verbose_name_plural": "۲. سوالات"},
        ),
        migrations.AlterModelOptions(
            name="survey",
            options={
                "verbose_name": "پرسشنامه",
                "verbose_name_plural": "۱. مدیریت پرسشنامه\u200cها",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="score_earned",
            field=models.IntegerField(default=0, verbose_name="امتیاز کسب شده"),
        ),
        migrations.AddField(
            model_name="survey",
            name="is_general",
            field=models.BooleanField(
                default=False, verbose_name="پرسشنامه عمومی (بدون وابستگی به محصول)"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="target_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crop_surveys",
                to="indicators.crop",
                verbose_name="مخصوص محصول خاص",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="target_user_type",
            field=models.CharField(
                choices=[
                    ("all", "عمومی (همه کاربران)"),
                    ("farmer", "فقط کشاورزان"),
                    ("official", "فقط پرسنل اداری / کارشناسان"),
                ],
                default="all",
                max_length=15,
                verbose_name="مخاطب هدف",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="پاسخ\u200cدهنده",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.CharField(
                blank=True,
                help_text="مثال: عالی|10، خوب|5، ضعیف|0 (گزینه\u200cها را با ویرگول جدا کنید)",
                max_length=500,
                null=True,
                verbose_name="گزینه\u200cها و امتیازها",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "متن کوتاه"),
                    ("textarea", "متن طولانی"),
                    ("number", "عدد"),
                    ("radio", "تک انتخابی (دارای امتیاز تحلیل)"),
                ],
                default="text",
                max_length=20,
                verbose_name="نوع سوال",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="accounts.company",
                verbose_name="شرکت/سازمان متولی",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="توضیحات/راهنمای پاسخ\u200cدهی"
            ),
        ),
    ]
