# Generated by Django 6.0 on 2026-06-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_alter_answer_options_alter_question_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="score_earned",
            field=models.IntegerField(default=0, verbose_name="امتیاز کسب شده (منسوخ)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.CharField(
                blank=True,
                help_text="گزینه\u200cها را با ویرگول (,) جدا کنید. (مثال: گزینه یک, گزینه دو)",
                max_length=500,
                null=True,
                verbose_name="گزینه\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "متن کوتاه"),
                    ("textarea", "متن طولانی"),
                    ("number", "عدد"),
                    ("radio", "تک انتخابی (گزینه\u200cای)"),
                ],
                default="text",
                max_length=20,
                verbose_name="نوع سوال",
            ),
        ),
        migrations.CreateModel(
            name="SurveyFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_name",
                    models.CharField(
                        help_text="مانند: شدت آبیاری در هکتار",
                        max_length=150,
                        verbose_name="نام متغیر خروجی",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("add", "جمع (+)"),
                            ("sub", "تفریق (-)"),
                            ("mul", "ضرب (*)"),
                            ("div", "تقسیم (/)"),
                        ],
                        max_length=10,
                        verbose_name="عملگر ریاضی",
                    ),
                ),
                (
                    "multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="به عنوان مثال برای تبدیل مترمربع به هکتار عدد 10000 وارد کنید، در غیر این صورت 1 بگذارید.",
                        verbose_name="ضریب نهایی تبدیل واحد",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="surveys.survey",
                        verbose_name="پرسشنامه مرجع",
                    ),
                ),
                (
                    "variable_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_variables_a",
                        to="surveys.question",
                        verbose_name="سوال اول (متغیر A)",
                    ),
                ),
                (
                    "variable_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_variables_b",
                        to="surveys.question",
                        verbose_name="سوال دوم (متغیر B)",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرمول محاسباتی",
                "verbose_name_plural": "۴. فرمول\u200cهای محاسباتی",
            },
        ),
        migrations.CreateModel(
            name="CalculatedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_value",
                    models.FloatField(verbose_name="مقدار نهایی محاسبه شده"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان محاسبه"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پاسخ\u200cدهنده",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="surveys.surveyformula",
                        verbose_name="فرمول اعمال شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "نتیجه تحلیل عددی",
                "verbose_name_plural": "۵. نتایج تحلیل\u200cهای عددی",
                "unique_together": {("user", "formula")},
            },
        ),
    ]
