# Generated by Django 6.0 on 2026-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0004_alter_answer_score_earned_alter_question_choices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyformula",
            name="survey",
        ),
        migrations.AlterField(
            model_name="surveyformula",
            name="result_name",
            field=models.CharField(
                help_text="مانند: شدت آبیاری در هکتار (حاصل ترکیب سوالات فرم\u200cهای مختلف)",
                max_length=150,
                verbose_name="نام متغیر خروجی ترکیبی",
            ),
        ),
    ]
