# Generated by Django 6.0 on 2026-06-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0010_alter_variabledefinition_unique_together_and_more"),
        ("surveys", "0005_remove_surveyformula_survey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.CharField(
                blank=True,
                help_text="گزینه\u200cها را با ویرگول (,) جدا کنید.",
                max_length=500,
                null=True,
                verbose_name="گزینه\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="surveyformula",
            name="multiplier",
            field=models.FloatField(default=1.0, verbose_name="ضریب نهایی تبدیل واحد"),
        ),
        migrations.AlterField(
            model_name="surveyformula",
            name="result_name",
            field=models.CharField(
                max_length=150, verbose_name="نام متغیر خروجی ترکیبی"
            ),
        ),
        migrations.CreateModel(
            name="QuestionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_responses",
                    models.IntegerField(default=0, verbose_name="کل پاسخ\u200cها"),
                ),
                (
                    "satisfaction_index",
                    models.FloatField(default=0.0, verbose_name="شاخص رضایت CSI"),
                ),
                (
                    "numerical_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="شاخص\u200cهای توصیفی عددی",
                    ),
                ),
                (
                    "choice_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="متریک\u200cهای فراوانی گزینه\u200cها",
                    ),
                ),
                (
                    "text_metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="خروجی متنی هوش مصنوعی"
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.question",
                        verbose_name="سوال مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحلیل آماری سوال",
                "verbose_name_plural": "۶. داشبورد تحلیلی سوالات",
            },
        ),
        migrations.CreateModel(
            name="SurveyKPIBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_name",
                    models.CharField(max_length=150, verbose_name="عنوان نگاشت"),
                ),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("question_csi", "شاخص رضایت سوال (CSI)"),
                            ("question_mean", "میانگین حسابی پاسخ عددی سوال"),
                            ("formula_output", "خروجی فرمول ترکیبی محاسباتی"),
                        ],
                        max_length=30,
                        verbose_name="نوع دیتای تزریقی",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="وضعیت اتصال"),
                ),
                (
                    "source_formula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveys.surveyformula",
                        verbose_name="فرمول منبع",
                    ),
                ),
                (
                    "source_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveys.question",
                        verbose_name="سوال منبع",
                    ),
                ),
                (
                    "target_variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicators.variabledefinition",
                        verbose_name="متغیر مقصد در شاخص\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "اتصال پرسشنامه به KPI",
                "verbose_name_plural": "۷. موتور همگام\u200cسازی شاخص\u200cها",
            },
        ),
    ]
