# Generated by Django 6.0 on 2026-02-11 23:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مزرعه / قطعه زمین')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='مرز جغرافیایی (Polygon)')),
                ('area_hectares', models.FloatField(blank=True, editable=False, null=True, verbose_name='مساحت (هکتار)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سامانه')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='کشاورز')),
            ],
            options={
                'verbose_name': 'مزرعه',
                'verbose_name_plural': 'مزارع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('ndvi_value', models.FloatField(blank=True, null=True, verbose_name='شاخص سبزینگی (NDVI)')),
                ('soil_moisture', models.FloatField(blank=True, null=True, verbose_name='رطوبت خاک (%)')),
                ('evapotranspiration', models.FloatField(blank=True, null=True, verbose_name='تبخیر و تعرق (mm)')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='maps/heatmaps/', verbose_name='تصویر هیت\u200cمپ')),
                ('legend_data', models.JSONField(blank=True, null=True, verbose_name='دیتای راهنما')),
                ('status_label', models.CharField(choices=[('good', 'مطلوب'), ('warning', 'نیازمند توجه'), ('critical', 'بحرانی')], default='good', max_length=50, verbose_name='وضعیت کلی')),
                ('ai_recommendation', models.TextField(verbose_name='توصیه هوش مصنوعی / متخصص')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='farms.farm', verbose_name='مزرعه')),
            ],
            options={
                'verbose_name': 'گزارش سلامت',
                'verbose_name_plural': 'گزارش\u200cهای سلامت',
                'ordering': ['-report_date'],
            },
        ),
    ]
