# Generated by Django 6.0 on 2026-02-21 10:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_region_polygon'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmhealthreport',
            options={'verbose_name': 'گزارش سلامت', 'verbose_name_plural': 'گزارش\u200cهای سلامت'},
        ),
        migrations.AddField(
            model_name='farm',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_farms', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس مسئول'),
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='شهرستان'),
        ),
        migrations.AddField(
            model_name='farm',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='وضعیت تایید'),
        ),
        migrations.AddField(
            model_name='farm',
            name='province',
            field=models.ForeignKey(limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_farms', to='accounts.region', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='مرز جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='farmhealthreport',
            name='ai_recommendation',
            field=models.TextField(verbose_name='توصیه متخصص'),
        ),
    ]
