# Generated by Django 6.0 on 2026-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farmhealthreport_options_farm_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhealthreport',
            name='ai_recommendation',
            field=models.TextField(blank=True, verbose_name='توصیه متخصص/هوش مصنوعی'),
        ),
    ]
