# Generated by Django 6.0 on 2026-04-19 10:06

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_chosen_region'),
        ('farms', '0003_alter_farmhealthreport_ai_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region', verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='province',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_farms', to='accounts.region', verbose_name='استان'),
        ),
    ]
