# Generated by Django 6.0 on 2026-05-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_customuser_company'),
        ('farms', '0004_alter_farm_city_alter_farm_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.company', verbose_name='سازمان/شرکت مرتبط'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='province',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_farms', to='accounts.region', verbose_name='استان'),
        ),
    ]
