# Generated by Django 6.0 on 2026-04-18 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_customuser_chosen_region'),
        ('farms', '0002_alter_farmhealthreport_options_farm_assigned_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('initial_stage_days', models.IntegerField(verbose_name='طول دوره ابتدایی (روز)')),
                ('development_stage_days', models.IntegerField(verbose_name='طول دوره توسعه (روز)')),
                ('mid_stage_days', models.IntegerField(verbose_name='طول دوره میانی (روز)')),
                ('late_stage_days', models.IntegerField(verbose_name='طول دوره انتهایی (روز)')),
                ('kc_initial', models.FloatField(verbose_name='ضریب ابتدایی (Kc Initial)')),
                ('kc_mid', models.FloatField(verbose_name='ضریب میانی (Kc Mid)')),
                ('kc_late', models.FloatField(verbose_name='ضریب انتهایی (Kc Late)')),
                ('max_soil_moisture_depletion', models.FloatField(default=30.0, help_text='زمانی که تبخیر تجمعی به این عدد رسید، سیستم پیشنهاد آبیاری می\u200cدهد', verbose_name='حد مجاز تخلیه رطوبت (میلی\u200cمتر)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region', verbose_name='منطقه (بخش)')),
            ],
            options={
                'verbose_name': 'ضریب گیاهی',
                'verbose_name_plural': 'ضریب\u200cهای گیاهی',
            },
        ),
        migrations.CreateModel(
            name='IrrigationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(verbose_name='تاریخ کاشت')),
                ('area_hectares', models.FloatField(verbose_name='مساحت زیر کشت (هکتار)')),
                ('irrigation_method', models.CharField(choices=[('surface', 'غرقابی'), ('drip', 'قطره\u200cای'), ('sprinkler', 'بارانی')], default='surface', max_length=50, verbose_name='روش آبیاری')),
                ('last_irrigation_date', models.DateField(blank=True, help_text='آخرین زمانی که کشاورز دکمه تایید آبیاری را زده است', null=True, verbose_name='تاریخ آخرین آبیاری واقعی')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='irrigation.cropfactor', verbose_name='محصول و منطقه')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_plans', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برنامه آبیاری',
                'verbose_name_plural': 'برنامه\u200cهای آبیاری',
            },
        ),
    ]
